package eu.kanade.tachiyomi.extension.en.kagane

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(
    name: String,
    val key: String,
    private val pairs: List<Pair<String, String>>,
) : Filter.Select<String>(name, pairs.map { it.first }.toTypedArray()) {
    val selected: String
        get() = pairs[state].second
}

// ----------- FILTER METADATA FOR SSR SEARCH PAGE -----------
// These lists are extracted from Kagane's SSR metadata (search page).
// Do not remove any comments.

// Source filter (hardcoded, SSR order)
class SourceFilter : UriPartFilter(
    "Source",
    "source",
    listOf(
        "All" to "",
        "Comikey" to "Comikey",
        "Day Comics" to "Day Comics",
        "INKR Comics" to "INKR Comics",
        "Lezhin" to "Lezhin",
        "Manta" to "Manta",
        "Others" to "Others",
        "Pocket Comics" to "Pocket Comics",
        "Tapas" to "Tapas",
        "Toomics" to "Toomics",
        "Webtoon" to "Webtoon",
    )
)

// Genre filter (SSR order)
class GenreFilter : UriPartFilter(
    "Genre",
    "genre",
    listOf(
        // SSR order preserved
        "All" to "",
        "Action" to "action",
        "Adult" to "adult",
        "Adventure" to "adventure",
        "All Ages" to "all ages",
        "Animals" to "animals",
        "Anime" to "anime",
        "Anime Tie-in" to "anime tie-in",
        "Anthropomorphic" to "anthropomorphic",
        "Avant Garde" to "avant garde",
        "Aventure" to "aventure",
        "Boys' Love" to "boys' love",
        "Cats" to "cats",
        "CGDCT" to "cgdct",
        "Childcare" to "childcare",
        "College" to "college",
        "Comedy" to "comedy",
        "Completed Series" to "completed series",
        "Crime" to "crime",
        "Crossdressing" to "crossdressing",
        "Delinquents" to "delinquents",
        "Detective" to "detective",
        "Doujinshi" to "doujinshi",
        "Drama" to "drama",
        "Drame" to "drame",
        "Dungeon / Labyrinth" to "dungeon / labyrinth",
        "Dystopian" to "dystopian",
        "Ecchi" to "ecchi",
        "Erotica" to "erotica",
        "Erotique" to "erotique",
        "Fant. Romance" to "fant. romance",
        "Fantastique" to "fantastique",
        "Fantasy" to "fantasy",
        "Gag Humor" to "gag humor",
        "Gender Bender" to "gender bender",
        "Girls' Love" to "girls' love",
        "Gore" to "gore",
        "Gourmet" to "gourmet",
        "Graphic Novel" to "graphic novel",
        "Harem" to "harem",
        "Heartwarming" to "heartwarming",
        "Hentai" to "hentai",
        "Histoires Courtes" to "histoires courtes",
        "Historical" to "historical",
        "Historique" to "historique",
        "Horreur" to "horreur",
        "Horror" to "horror",
        "Idols (Male)" to "idols (male)",
        "Informative" to "informative",
        "Inspirational" to "inspirational",
        "Int'l Manga" to "int'l manga",
        "Isekai" to "isekai",
        "Iyashikei" to "iyashikei",
        "Josei" to "josei",
        "Kids" to "kids",
        "LGBTQ" to "lgbtq",
        "LGBTQ+" to "lgbtq+",
        "Lolicon" to "lolicon",
        "Love Polygon" to "love polygon",
        "Love Status Quo" to "love status quo",
        "Magic" to "magic",
        "Magical Girls" to "magical girls",
        "Magical Sex Shift" to "magical sex shift",
        "Mahou Shoujo" to "mahou shoujo",
        "Manga" to "manga",
        "Manhwa" to "manhwa",
        "Martial Arts" to "martial arts",
        "Mature" to "mature",
        "Mecha" to "mecha",
        "Medical" to "medical",
        "Military" to "military",
        "Mod. Romance" to "mod. romance",
        "Monster Girls" to "monster girls",
        "Music" to "music",
        "Mystery" to "mystery",
        "Mystère" to "mystère",
        "Myth" to "myth",
        "Mythology" to "mythology",
        "New" to "new",
        "Noble Romance" to "noble romance",
        "Non-human" to "non-human",
        "Office" to "office",
        "One Shot" to "one shot",
        "Organized Crime" to "organized crime",
        "Otaku Culture" to "otaku culture",
        "Pets" to "pets",
        "Philosophical" to "philosophical",
        "Pocoexclucive" to "pocoexclucive",
        "Psychological" to "psychological",
        "Psychologique" to "psychologique",
        "Reincarnation" to "reincarnation",
        "Reverse Harem" to "reverse harem",
        "Romance" to "romance",
        "Royalty/Nobility" to "royalty/nobility",
        "School" to "school",
        "School Life" to "school life",
        "Sci-fi" to "sci-fi",
        "Science Fiction" to "science fiction",
        "Seinen" to "seinen",
        "Short" to "short",
        "Short Story" to "short story",
        "Shotacon" to "shotacon",
        "Shoujo" to "shoujo",
        "Shounen" to "shounen",
        "Showbiz" to "showbiz",
        "Shōjo-ai" to "shōjo-ai",
        "Shōnen-ai" to "shōnen-ai",
        "Slice of Life" to "slice of life",
        "Smut" to "smut",
        "Space" to "space",
        "Sports" to "sports",
        "Strategy Game" to "strategy game",
        "Super Power" to "super power",
        "Superhero" to "superhero",
        "Supernatural" to "supernatural",
        "Surnaturel" to "surnaturel",
        "Survival" to "survival",
        "Suspense" to "suspense",
        "Team Sports" to "team sports",
        "Teens' Love" to "teens' love",
        "Thriller" to "thriller",
        "Time Travel" to "time travel",
        "Tragedy" to "tragedy",
        "Tragique" to "tragique",
        "Uncensored" to "uncensored",
        "Urban Fantasy" to "urban fantasy",
        "Vampire" to "vampire",
        "Vanilla" to "vanilla",
        "Video Game" to "video game",
        "Video Games / Game Adaptation / Game Elements" to "video games / game adaptation / game elements",
        "Villainess" to "villainess",
        "Visual Arts" to "visual arts",
        "Workplace" to "workplace",
        "Wuxia" to "wuxia",
        "Xuanhuan" to "xuanhuan",
        "Yonkoma" to "yonkoma",
    )
)

// Tag filter (SSR order, huge list, will be sent next message)
class TagFilter : UriPartFilter(
    "Tag",
    "tag",
    listOf(
        // --- FULL TAG LIST GOES HERE ---
        // Do not remove any comments!
    )
)

// Sort filter
class SortFilter : UriPartFilter(
    "Sort By",
    "sort",
    listOf(
        "Relevance" to "relevance",
        "Latest" to "latest",
        "By Name" to "name",
        "Books count" to "books-count",
        "Created at" to "created-at",
    ),
)
