package eu.kanade.tachiyomi.extension.all.batoto

import eu.kanade.tachiyomi.source.model.Filter

class SelectFilterOption(val name: String, val value: String)
class CheckboxFilterOption(val value: String, name: String, default: Boolean = false) : Filter.CheckBox(name, default)
class TriStateFilterOption(val value: String, name: String, default: Int = 0) : Filter.TriState(name, default)

abstract class SelectFilter(name: String, private val options: List<SelectFilterOption>, default: Int = 0) : Filter.Select<String>(name, options.map { it.name }.toTypedArray(), default) {
    val selected: String
        get() = options[state].value
}

abstract class CheckboxGroupFilter(name: String, options: List<CheckboxFilterOption>) : Filter.Group<CheckboxFilterOption>(name, options) {
    val selected: List<String>
        get() = state.filter { it.state }.map { it.value }
}

abstract class TriStateGroupFilter(name: String, options: List<TriStateFilterOption>) : Filter.Group<TriStateFilterOption>(name, options) {
    val included: List<String>
        get() = state.filter { it.isIncluded() }.map { it.value }

    val excluded: List<String>
        get() = state.filter { it.isExcluded() }.map { it.value }
}

abstract class TextFilter(name: String) : Filter.Text(name)

class SortFilter(sortables: Array<String>) : Filter.Sort("Sort", sortables, Selection(5, false))
class StatusFilter(options: List<SelectFilterOption>, default: Int) : SelectFilter("Status", options, default)
class OriginGroupFilter(options: List<CheckboxFilterOption>) : CheckboxGroupFilter("Origin", options)
class GenreGroupFilter(options: List<TriStateFilterOption>) : TriStateGroupFilter("Genre", options)
class MinChapterTextFilter : TextFilter("Min. Chapters")
class MaxChapterTextFilter : TextFilter("Max. Chapters")
class LangGroupFilter(options: List<CheckboxFilterOption>) : CheckboxGroupFilter("Languages", options)
class LetterFilter(options: List<SelectFilterOption>, default: Int) : SelectFilter("Letter matching mode (Slow)", options, default)
class UtilsFilter(options: List<SelectFilterOption>, default: Int) : SelectFilter("Utils comic list", options, default)
class HistoryFilter(options: List<SelectFilterOption>, default: Int) : SelectFilter("Personal list", options, default)

fun getLetterFilter() = listOf(
    SelectFilterOption("Disabled", "disabled"),
    SelectFilterOption("Enabled", "enabled"),
)

fun getSortFilter() = listOf(
    SelectFilterOption("Z-A", "title"),
    SelectFilterOption("Last Updated", "update"),
    SelectFilterOption("Newest Added", "create"),
    SelectFilterOption("Most Views Totally", "views_a"),
    SelectFilterOption("Most Views 365 days", "views_y"),
    SelectFilterOption("Most Views 30 days", "views_m"),
    SelectFilterOption("Most Views 7 days", "views_w"),
    SelectFilterOption("Most Views 24 hours", "views_d"),
    SelectFilterOption("Most Views 60 minutes", "views_h"),
)

fun getHistoryFilter() = listOf(
    SelectFilterOption("None", ""),
    SelectFilterOption("My History", "history"),
    SelectFilterOption("My Updates", "updates"),
)

fun getUtilsFilter() = listOf(
    SelectFilterOption("None", ""),
    SelectFilterOption("Comics: I Created", "i-created"),
    SelectFilterOption("Comics: I Modified", "i-modified"),
    SelectFilterOption("Comics: I Uploaded", "i-uploaded"),
    SelectFilterOption("Comics: Authorized to me", "i-authorized"),
    SelectFilterOption("Comics: Draft Status", "status-draft"),
    SelectFilterOption("Comics: Hidden Status", "status-hidden"),
    SelectFilterOption("Ongoing and Not updated in 30-60 days", "not-updated-30-60"),
    SelectFilterOption("Ongoing and Not updated in 60-90 days", "not-updated-60-90"),
    SelectFilterOption("Ongoing and Not updated in 90-180 days", "not-updated-90-180"),
    SelectFilterOption("Ongoing and Not updated in 180-360 days", "not-updated-180-360"),
    SelectFilterOption("Ongoing and Not updated in 360-1000 days", "not-updated-360-1000"),
    SelectFilterOption("Ongoing and Not updated more than 1000 days", "not-updated-1000"),
)

fun getStatusFilter() = listOf(
    SelectFilterOption("All", ""),
    SelectFilterOption("Pending", "pending"),
    SelectFilterOption("Ongoing", "ongoing"),
    SelectFilterOption("Completed", "completed"),
    SelectFilterOption("Hiatus", "hiatus"),
    SelectFilterOption("Cancelled", "cancelled"),
)

fun getOrginFilter() = listOf(
    CheckboxFilterOption("zh", "Chinese"),
    CheckboxFilterOption("en", "English"),
    CheckboxFilterOption("ja", "Japanese"),
    CheckboxFilterOption("ko", "Korean"),
    CheckboxFilterOption("af", "Afrikaans"),
    CheckboxFilterOption("sq", "Albanian"),
    CheckboxFilterOption("am", "Amharic"),
    CheckboxFilterOption("ar", "Arabic"),
    CheckboxFilterOption("hy", "Armenian"),
    CheckboxFilterOption("az", "Azerbaijani"),
    CheckboxFilterOption("be", "Belarusian"),
    CheckboxFilterOption("bn", "Bengali"),
    CheckboxFilterOption("bs", "Bosnian"),
    CheckboxFilterOption("bg", "Bulgarian"),
    CheckboxFilterOption("my", "Burmese"),
    CheckboxFilterOption("km", "Cambodian"),
    CheckboxFilterOption("ca", "Catalan"),
    CheckboxFilterOption("ceb", "Cebuano"),
    CheckboxFilterOption("zh_hk", "Chinese (Cantonese)"),
    CheckboxFilterOption("zh_tw", "Chinese (Traditional)"),
    CheckboxFilterOption("hr", "Croatian"),
    CheckboxFilterOption("cs", "Czech"),
    CheckboxFilterOption("da", "Danish"),
    CheckboxFilterOption("nl", "Dutch"),
    CheckboxFilterOption("en_us", "English (United States)"),
    CheckboxFilterOption("eo", "Esperanto"),
    CheckboxFilterOption("et", "Estonian"),
    CheckboxFilterOption("fo", "Faroese"),
    CheckboxFilterOption("fil", "Filipino"),
    CheckboxFilterOption("fi", "Finnish"),
    CheckboxFilterOption("fr", "French"),
    CheckboxFilterOption("ka", "Georgian"),
    CheckboxFilterOption("de", "German"),
    CheckboxFilterOption("el", "Greek"),
    CheckboxFilterOption("gn", "Guarani"),
    CheckboxFilterOption("gu", "Gujarati"),
    CheckboxFilterOption("ht", "Haitian Creole"),
    CheckboxFilterOption("ha", "Hausa"),
    CheckboxFilterOption("he", "Hebrew"),
    CheckboxFilterOption("hi", "Hindi"),
    CheckboxFilterOption("hu", "Hungarian"),
    CheckboxFilterOption("is", "Icelandic"),
    CheckboxFilterOption("ig", "Igbo"),
    CheckboxFilterOption("id", "Indonesian"),
    CheckboxFilterOption("ga", "Irish"),
    CheckboxFilterOption("it", "Italian"),
    CheckboxFilterOption("jv", "Javanese"),
    CheckboxFilterOption("kn", "Kannada"),
    CheckboxFilterOption("kk", "Kazakh"),
    CheckboxFilterOption("ku", "Kurdish"),
    CheckboxFilterOption("ky", "Kyrgyz"),
    CheckboxFilterOption("lo", "Laothian"),
    CheckboxFilterOption("lv", "Latvian"),
    CheckboxFilterOption("lt", "Lithuanian"),
    CheckboxFilterOption("lb", "Luxembourgish"),
    CheckboxFilterOption("mk", "Macedonian"),
    CheckboxFilterOption("mg", "Malagasy"),
    CheckboxFilterOption("ms", "Malay"),
    CheckboxFilterOption("ml", "Malayalam"),
    CheckboxFilterOption("mt", "Maltese"),
    CheckboxFilterOption("mi", "Maori"),
    CheckboxFilterOption("mr", "Marathi"),
    CheckboxFilterOption("mo", "Moldavian"),
    CheckboxFilterOption("mn", "Mongolian"),
    CheckboxFilterOption("ne", "Nepali"),
    CheckboxFilterOption("no", "Norwegian"),
    CheckboxFilterOption("ny", "Nyanja"),
    CheckboxFilterOption("ps", "Pashto"),
    CheckboxFilterOption("fa", "Persian"),
    CheckboxFilterOption("pl", "Polish"),
    CheckboxFilterOption("pt", "Portuguese"),
    CheckboxFilterOption("pt_br", "Portuguese (Brazil)"),
    CheckboxFilterOption("ro", "Romanian"),
    CheckboxFilterOption("rm", "Romansh"),
    CheckboxFilterOption("ru", "Russian"),
    CheckboxFilterOption("sm", "Samoan"),
    CheckboxFilterOption("sr", "Serbian"),
    CheckboxFilterOption("sh", "Serbo-Croatian"),
    CheckboxFilterOption("st", "Sesotho"),
    CheckboxFilterOption("sn", "Shona"),
    CheckboxFilterOption("sd", "Sindhi"),
    CheckboxFilterOption("si", "Sinhalese"),
    CheckboxFilterOption("sk", "Slovak"),
    CheckboxFilterOption("sl", "Slovenian"),
    CheckboxFilterOption("so", "Somali"),
    CheckboxFilterOption("es", "Spanish"),
    CheckboxFilterOption("es_419", "Spanish (Latin America)"),
    CheckboxFilterOption("sw", "Swahili"),
    CheckboxFilterOption("sv", "Swedish"),
    CheckboxFilterOption("tg", "Tajik"),
    CheckboxFilterOption("ta", "Tamil"),
    CheckboxFilterOption("th", "Thai"),
    CheckboxFilterOption("ti", "Tigrinya"),
    CheckboxFilterOption("to", "Tonga"),
    CheckboxFilterOption("tr", "Turkish"),
    CheckboxFilterOption("tk", "Turkmen"),
    CheckboxFilterOption("uk", "Ukrainian"),
    CheckboxFilterOption("ur", "Urdu"),
    CheckboxFilterOption("uz", "Uzbek"),
    CheckboxFilterOption("vi", "Vietnamese"),
    CheckboxFilterOption("yo", "Yoruba"),
    CheckboxFilterOption("zu", "Zulu"),
    CheckboxFilterOption("_t", "Other"),
)

fun getGenreFilter() = listOf(
    TriStateFilterOption("artbook", "Artbook"),
    TriStateFilterOption("cartoon", "Cartoon"),
    TriStateFilterOption("comic", "Comic"),
    TriStateFilterOption("doujinshi", "Doujinshi"),
    TriStateFilterOption("imageset", "Imageset"),
    TriStateFilterOption("manga", "Manga"),
    TriStateFilterOption("manhua", "Manhua"),
    TriStateFilterOption("manhwa", "Manhwa"),
    TriStateFilterOption("webtoon", "Webtoon"),
    TriStateFilterOption("western", "Western"),
    TriStateFilterOption("shoujo", "Shoujo(G)"),
    TriStateFilterOption("shounen", "Shounen(B)"),
    TriStateFilterOption("josei", "Josei(W)"),
    TriStateFilterOption("seinen", "Seinen(M)"),
    TriStateFilterOption("yuri", "Yuri(GL)"),
    TriStateFilterOption("yaoi", "Yaoi(BL)"),
    TriStateFilterOption("futa", "Futa(WL)"),
    TriStateFilterOption("bara", "Bara(ML)"),
    TriStateFilterOption("gore", "Gore"),
    TriStateFilterOption("bloody", "Bloody"),
    TriStateFilterOption("violence", "Violence"),
    TriStateFilterOption("ecchi", "Ecchi"),
    TriStateFilterOption("adult", "Adult"),
    TriStateFilterOption("mature", "Mature"),
    TriStateFilterOption("smut", "Smut"),
    TriStateFilterOption("hentai", "Hentai"),
    TriStateFilterOption("_4_koma", "4-Koma"),
    TriStateFilterOption("action", "Action"),
    TriStateFilterOption("adaptation", "Adaptation"),
    TriStateFilterOption("adventure", "Adventure"),
    TriStateFilterOption("age_gap", "Age Gap"),
    TriStateFilterOption("aliens", "Aliens"),
    TriStateFilterOption("animals", "Animals"),
    TriStateFilterOption("anthology", "Anthology"),
    TriStateFilterOption("award_winning", "Award Winning"),
    TriStateFilterOption("beasts", "Beasts"),
    TriStateFilterOption("bodyswap", "Bodyswap"),
    TriStateFilterOption("cars", "Cars"),
    TriStateFilterOption("cheating_infidelity", "Cheating/Infidelity"),
    TriStateFilterOption("childhood_friends", "Childhood Friends"),
    TriStateFilterOption("college_life", "College Life"),
    TriStateFilterOption("comedy", "Comedy"),
    TriStateFilterOption("contest_winning", "Contest Winning"),
    TriStateFilterOption("cooking", "Cooking"),
    TriStateFilterOption("crime", "Crime"),
    TriStateFilterOption("crossdressing", "Crossdressing"),
    TriStateFilterOption("delinquents", "Delinquents"),
    TriStateFilterOption("dementia", "Dementia"),
    TriStateFilterOption("demons", "Demons"),
    TriStateFilterOption("drama", "Drama"),
    TriStateFilterOption("dungeons", "Dungeons"),
    TriStateFilterOption("emperor_daughter", "Emperor's Daughter"),
    TriStateFilterOption("fantasy", "Fantasy"),
    TriStateFilterOption("fan_colored", "Fan-Colored"),
    TriStateFilterOption("fetish", "Fetish"),
    TriStateFilterOption("full_color", "Full Color"),
    TriStateFilterOption("game", "Game"),
    TriStateFilterOption("gender_bender", "Gender Bender"),
    TriStateFilterOption("genderswap", "Genderswap"),
    TriStateFilterOption("ghosts", "Ghosts"),
    TriStateFilterOption("gyaru", "Gyaru"),
    TriStateFilterOption("harem", "Harem"),
    TriStateFilterOption("harlequin", "Harlequin"),
    TriStateFilterOption("historical", "Historical"),
    TriStateFilterOption("horror", "Horror"),
    TriStateFilterOption("incest", "Incest"),
    TriStateFilterOption("isekai", "Isekai"),
    TriStateFilterOption("kids", "Kids"),
    TriStateFilterOption("loli", "Loli"),
    TriStateFilterOption("magic", "Magic"),
    TriStateFilterOption("magical_girls", "Magical Girls"),
    TriStateFilterOption("martial_arts", "Martial Arts"),
    TriStateFilterOption("mecha", "Mecha"),
    TriStateFilterOption("medical", "Medical"),
    TriStateFilterOption("military", "Military"),
    TriStateFilterOption("monster_girls", "Monster Girls"),
    TriStateFilterOption("monsters", "Monsters"),
    TriStateFilterOption("music", "Music"),
    TriStateFilterOption("mystery", "Mystery"),
    TriStateFilterOption("netorare", "Netorare/NTR"),
    TriStateFilterOption("ninja", "Ninja"),
    TriStateFilterOption("office_workers", "Office Workers"),
    TriStateFilterOption("omegaverse", "Omegaverse"),
    TriStateFilterOption("oneshot", "Oneshot"),
    TriStateFilterOption("parody", "Parody"),
    TriStateFilterOption("philosophical", "Philosophical"),
    TriStateFilterOption("police", "Police"),
    TriStateFilterOption("post_apocalyptic", "Post-Apocalyptic"),
    TriStateFilterOption("psychological", "Psychological"),
    TriStateFilterOption("regression", "Regression"),
    TriStateFilterOption("reincarnation", "Reincarnation"),
    TriStateFilterOption("reverse_harem", "Reverse Harem"),
    TriStateFilterOption("reverse_isekai", "Reverse Isekai"),
    TriStateFilterOption("romance", "Romance"),
    TriStateFilterOption("royal_family", "Royal Family"),
    TriStateFilterOption("royalty", "Royalty"),
    TriStateFilterOption("samurai", "Samurai"),
    TriStateFilterOption("school_life", "School Life"),
    TriStateFilterOption("sci_fi", "Sci-Fi"),
    TriStateFilterOption("shota", "Shota"),
    TriStateFilterOption("shoujo_ai", "Shoujo Ai"),
    TriStateFilterOption("shounen_ai", "Shounen Ai"),
    TriStateFilterOption("showbiz", "Showbiz"),
    TriStateFilterOption("slice_of_life", "Slice of Life"),
    TriStateFilterOption("sm_bdsm", "SM/BDSM/SUB-DOM"),
    TriStateFilterOption("space", "Space"),
    TriStateFilterOption("sports", "Sports"),
    TriStateFilterOption("super_power", "Super Power"),
    TriStateFilterOption("superhero", "Superhero"),
    TriStateFilterOption("supernatural", "Supernatural"),
    TriStateFilterOption("survival", "Survival"),
    TriStateFilterOption("thriller", "Thriller"),
    TriStateFilterOption("time_travel", "Time Travel"),
    TriStateFilterOption("tower_climbing", "Tower Climbing"),
    TriStateFilterOption("traditional_games", "Traditional Games"),
    TriStateFilterOption("tragedy", "Tragedy"),
    TriStateFilterOption("transmigration", "Transmigration"),
    TriStateFilterOption("vampires", "Vampires"),
    TriStateFilterOption("video_games", "Video Games"),
    TriStateFilterOption("villainess", "Villainess"),
    TriStateFilterOption("virtual_reality", "Virtual Reality"),
    TriStateFilterOption("wuxia", "Wuxia"),
    TriStateFilterOption("xianxia", "Xianxia"),
    TriStateFilterOption("xuanhuan", "Xuanhuan"),
    TriStateFilterOption("zombies", "Zombies"),
)

fun getLangFilter() = listOf(
    CheckboxFilterOption("en", "English"),
    CheckboxFilterOption("ar", "Arabic"),
    CheckboxFilterOption("bg", "Bulgarian"),
    CheckboxFilterOption("zh", "Chinese"),
    CheckboxFilterOption("cs", "Czech"),
    CheckboxFilterOption("da", "Danish"),
    CheckboxFilterOption("nl", "Dutch"),
    CheckboxFilterOption("fil", "Filipino"),
    CheckboxFilterOption("fi", "Finnish"),
    CheckboxFilterOption("fr", "French"),
    CheckboxFilterOption("de", "German"),
    CheckboxFilterOption("el", "Greek"),
    CheckboxFilterOption("he", "Hebrew"),
    CheckboxFilterOption("hi", "Hindi"),
    CheckboxFilterOption("hu", "Hungarian"),
    CheckboxFilterOption("id", "Indonesian"),
    CheckboxFilterOption("it", "Italian"),
    CheckboxFilterOption("ja", "Japanese"),
    CheckboxFilterOption("ko", "Korean"),
    CheckboxFilterOption("ms", "Malay"),
    CheckboxFilterOption("pl", "Polish"),
    CheckboxFilterOption("pt", "Portuguese"),
    CheckboxFilterOption("pt_br", "Portuguese (Brazil)"),
    CheckboxFilterOption("ro", "Romanian"),
    CheckboxFilterOption("ru", "Russian"),
    CheckboxFilterOption("es", "Spanish"),
    CheckboxFilterOption("es_419", "Spanish (Latin America)"),
    CheckboxFilterOption("sv", "Swedish"),
    CheckboxFilterOption("th", "Thai"),
    CheckboxFilterOption("tr", "Turkish"),
    CheckboxFilterOption("uk", "Ukrainian"),
    CheckboxFilterOption("vi", "Vietnamese"),
)
